services:
  - type: web
    name: attendance-app
    env: docker
    plan: free
    repo: https://github.com/310Masahide/Attendance-Tutorial
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
