services:
  - type: web
    name: attendance-app
    env: ruby
    plan: free
    repo: https://github.com/310Masahide/Attendance-Tutorial
    rootDir: attendance_app
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec rails db:migrate && bundle exec rails server -p $PORT -e production
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: WEB_CONCURRENCY
        value: "2"
