// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditBasicInfoController from "./edit_basic_info_controller"
application.register("edit-basic-info", EditBasicInfoController)
