source "https://rubygems.org"

ruby ">= 3.2.0", "< 4.0"

gem "rails", "~> 7.1.0"
gem 'faker'
gem "sprockets-rails"
gem "mysql2", "~> 0.5"
gem "puma", ">= 5.0"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]
gem "bootsnap", require: false
gem 'bootstrap-sass'
gem 'bcrypt'
gem 'will_paginate', '~> 3.3'
gem 'bootstrap-will_paginate', '1.0.0'
gem 'rails-i18n'
gem 'capybara', '>= 3.26'
gem 'selenium-webdriver'
gem 'webdrivers'
gem 'rails-flog', require: 'flog'
gem 'rspec-rails'
gem "factory_bot_rails"
gem 'faker'
gem 'database_cleaner'
gem 'rails-controller-testing'


group :development, :test do
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
  gem "web-console"
end

group :test do
 gem 'capybara', '>= 3.26'
 gem 'selenium-webdriver'
 gem 'webdrivers'
 gem 'rails-flog', require: 'flog'
 gem 'rspec-rails'
 gem "factory_bot_rails"
 gem 'database_cleaner'
 gem 'rails-controller-testing'
 gem 'amazing_print', '< 2.0.0'
end
